- name: Install nginx
  apt: name=nginx
- name: Start enable nginx service
  systemd: name=nginx state=started enabled=yes masked=no
- name: Remove default config
  file: path=/etc/nginx/sites-enabled/default state=absent
- name: Add the config
  template: src=site_config.j2 dest="/etc/nginx/sites-enabled/{{ server_name }}"
  notify: restart nginx
