- name: Installs php
  apt: name={{ item }}
  with_items:
    - php5-fpm
    - php5-apcu
    - php5-intl
    - php5-gd
    - php5-cli
    - php5-mysql
    - php5-ldap
    - php5-curl
- name: Add the php config
  template: src=php.ini.j2 dest="/etc/php5/fpm/php.ini"
  notify: restart php-fpm
